2024-01-25 20:40:36: Experiment log path in: D:\omer\ST-SSL\experiments\Careem\20240125-204036
2024-01-25 20:40:36: Experiment configs are: Namespace(seed=31, device='cuda', mode='train', best_path='None', debug=False, data_dir='data', dataset='Careem', input_length=19, batch_size=32, test_batch_size=32, graph_file='data/Careem/adj_mx.npz', d_input=1, d_output=1, d_model=64, dropout=0.2, percent=0.1, shm_temp=0.5, nmb_prototype=2, yita=1, epochs=1, lr_init=0.001, early_stop=True, early_stop_patience=150, grad_norm=True, max_grad_norm=5, use_dwa=True, temp=4, num_nodes=285, log_dir='D:\\omer\\ST-SSL\\experiments\\Careem\\20240125-204036')
2024-01-25 20:40:43: *******Train Epoch 1: averaged Loss : 9.391333
2024-01-25 20:40:43: *******Val Epoch 1: averaged Loss : 8.056190
2024-01-25 20:40:43: **************Current best model saved to D:\omer\ST-SSL\experiments\Careem\20240125-204036\best_model.pth
2024-01-25 20:40:43: == Training finished.
Total training time: 0.12 min	best loss: 8.0562	best epoch: 1	
2024-01-25 20:40:43: == Test results.
2024-01-25 20:40:43: Traceback (most recent call last):
  File "D:\omer\ST-SSL\main.py", line 59, in model_supervisor
    results = trainer.train() # best_eval_loss, best_epoch
              ^^^^^^^^^^^^^^^
  File "D:\omer\ST-SSL\model\trainer.py", line 155, in train
    test_results = self.test(self.model, self.test_loader, self.scaler,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\omer\ST-SSL\model\trainer.py", line 208, in test
    data[:, t, :, :] = prediction_buffer[t]
    ~~~~^^^^^^^^^^^^
RuntimeError: expand(torch.cuda.FloatTensor{[32, 1, 285, 1]}, size=[32, 285, 1]): the number of sizes provided (3) must be greater or equal to the number of dimensions in the tensor (4)

