2024-01-24 12:15:51: Experiment log path in: D:\omer\ST-SSL\experiments\NYCBike1\20240124-121551
2024-01-24 12:15:51: Experiment configs are: Namespace(batch_size=32, best_path='None', d_input=2, d_model=64, d_output=2, data_dir='data', dataset='NYCBike1', debug=False, device='cuda:0', dropout=0.2, early_stop=True, early_stop_patience=15, epochs=100, grad_norm=True, graph_file='data/NYCBike1/adj_mx.npz', input_length=19, log_dir='D:\\omer\\ST-SSL\\experiments\\NYCBike1\\20240124-121551', lr_init=0.001, max_grad_norm=5, mode='train', nmb_prototype=6, num_nodes=128, percent=0.1, seed=31, shm_temp=0.5, temp=4, test_batch_size=32, use_dwa=True, yita=0.6)
2024-01-24 12:15:51: Traceback (most recent call last):
  File "main.py", line 59, in model_supervisor
    results = trainer.train() # best_eval_loss, best_epoch
  File "D:\omer\ST-SSL\model\trainer.py", line 109, in train
    train_epoch_loss, loss_t = self.train_epoch(epoch, loss_weights)
  File "D:\omer\ST-SSL\model\trainer.py", line 57, in train_epoch
    repr1, repr2 = self.model(data, self.graph) # nvc
  File "C:\Users\IST\.conda\envs\ST-SSL\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\IST\.conda\envs\ST-SSL\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\omer\ST-SSL\model\models.py", line 35, in forward
    graph2 = aug_topology(s_sim_mx, graph, percent=self.args.percent*2)
  File "D:\omer\ST-SSL\model\aug.py", line 54, in aug_topology
    drop_prob = torch.softmax(sim_mx[edge_mask], dim=0)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

